server:
  port: 4766
spring:
  application:
    name: service-feign
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:4761/eureka
feign:
  hystrix:
    enabled: true