server:
  port: 4780
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shaunPaule/SpringcloudConfig
          search-paths: respo
          username:
          password: 
      label: master

